### ISSUE TITLE
Test controller that use form processing 

### ISSUE THREAD

**Issue by ronypur** [fideloper/Implementing-Laravel#29]
Is there any working example of testing on controller that use form processing as written in the book? I'm little confuse about how exactly to test controller with pattern like that. Is it necessary to test each method in the controller or is it enough just to test the the form processing class as a unit?

**Comment by fideloper** [comment]
I avoid testing controllers (having any http mechanism in tests) using this
style of coding  -- I just test the use cases/form classes.

You're question "is it necessary to test each method" - there's no strict
or necessary way to do anything!

It should be noted, I haven't updated the book on this, but I'm now using
Command Buses a lot - they are a bit more refined way of doing the same
thing. Laravel 5 will have them baked in.

**Comment by ronypur** [comment]
Thank you Chris, it's a lot more clearer now.
