### ISSUE TITLE
FatalErrorException - Class 'Memcached' not found

### ISSUE THREAD

**Issue by wmlockhart** [fideloper/Implementing-Laravel#6]
Hi Chris,

I have purchased and just finished reading your book. It's excellent - Thanks.

I really like the way you structure the sample application and I'm very keen to use your approach in an upcoming application of my own.

I downloaded the most recent release of the same application from GitHub - and I followed the instructions on installing the application. We I ran the sample application I got the error message 'FatalErrorException - Class 'Memcached' not found' which occured at line 40 in 'vendor\laravel\framework\src\Illuminate\Cache\MemcachedConnector.php'

My development environment is XAMPP running on Windows 7, so I followed the instructions here: http://www.leonardaustin.com/t... to install memcached on XAMPP running Windows 7. The installation appears to be working well with no errors when running the test code provided by the author of the article.

However, after restarting my development environment I still get the error message 'FatalErrorException - Class 'Memcached' not found' when I try to run your sample application.

Am I missing some specific configuration of memcached required for Laravel 4 or your sample application?

I have successfully developed and ran Laravel 4 applications on my development machine previously, although not with memcached.

Any help would be greatly appreciated as I am keen to explore your sample application further and learn more.

Thanks in advance.

Kind Regards

Walter

**Comment by wpjCode** [comment]
Your mean is：Windows System can‘t use the PHP memcached class??
